version: '3.9'

services:
  sveltekit:
    image: node:20
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "${SVELTEKIT_PORT}:${SVELTEKIT_PORT}"
    env_file:
      - .env
    command: >
      sh -c "yarn install && 
             if [ \"$NODE_ENV\" = \"dev\" ]; then yarn dev; 
             else yarn build && yarn preview; fi"

  pocketbase:
    image: alpine:latest
    working_dir: /pb
    volumes:
      - ./pocketbase:/pb
    ports:
      - "8090:8090"
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "/pb/pocketbase serve --http=0.0.0.0:8090 & /pb/init.sh"]

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
      - ./minio/init.sh:/init.sh  # Mount the init script
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "minio server /data --console-address :9090 & /init.sh"]

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    env_file:
      - .env
    command: ["bin/maildev"]

volumes:
  minio_data:
